// * Zombie Swarm RPG Include * //
// * Includes by --chcode & berkch * //

// Sets
native zs_rpg_set_level(id, amount);
native zs_rpg_set_exp(id, amount);
native zs_rpg_set_health(id, amount);
native zs_rpg_set_attack(id, amount);
native zs_rpg_set_speed(id, amount);
native zs_rpg_set_deffence(id, amount);
native zs_rpg_set_points(id, amount);

// Gets
native zs_rpg_get_level(id);
native zs_rpg_get_exp(id);
native zs_rpg_get_health(id);
native zs_rpg_get_attack(id);
native zs_rpg_get_speed(id);
native zs_rpg_get_deffence(id);
native zs_rpg_get_points(id);